version: '3'

services:
  demo:
      build: ./
      restart: always
      environment:
        - var1=welcome to docker 101
        - var2=this is how we pass var between .py file
        - var3=0
      command: python -u src/main.py